In [1]:
import pandas as pd

In [2]:
import sys
print(sys.executable)

c:\Users\maggi\anaconda3\python.exe

In [3]:
sectors_df = pd.read_csv("bls_allsectors_2024.csv")  
sectors_df

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\3764669674.py:1: DtypeWarning: Columns (3,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  sectors_df = pd.read_csv("bls_allsectors_2024.csv")

,naics2,AREA,AREA_TITLE,NAICS,NAICS_TITLE,I_GROUP,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,...,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY,Unnamed: 27,release
0,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,00-0000,All Occupations,total,"5,260",...,35.25,"28,730","36,410","47,560","57,030","73,310",NaN,NaN,NaN,NaN
1,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,11-0000,Management Occupations,major,100,...,68.43,"75,140","85,870","102,590","124,420","142,340",NaN,NaN,NaN,NaN
2,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,11-1021,General and Operations Managers,detailed,70,...,75.46,"73,810","83,810","97,570","130,280","156,960",NaN,NaN,NaN,NaN
3,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,13-0000,Business and Financial Operations Occupations,major,60,...,62.61,"43,180","50,890","72,920","81,470","130,220",NaN,NaN,NaN,NaN
4,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,19-0000,"Life, Physical, and Social Science Occupations",major,90,...,43.69,"39,970","54,610","57,000","82,080","90,880",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861917,99,72,Puerto Rico,999300,"Local Government, excluding Schools and Hospit...",4-digit,53-3052,"Bus Drivers, Transit and Intercity",detailed,130,...,21.59,"21,630","22,620","22,620","44,900","44,900",NaN,NaN,NaN,NaN
861918,99,72,Puerto Rico,999300,"Local Government, excluding Schools and Hospit...",4-digit,53-3053,Shuttle Drivers and Chauffeurs,detailed,130,...,19.64,"19,760","19,760","20,260","26,110","40,860",NaN,NaN,NaN,NaN
861919,99,72,Puerto Rico,999300,"Local Government, excluding Schools and Hospit...",4-digit,53-7062,"Laborers and Freight, Stock, and Material Move...",detailed,460,...,13.59,"19,760","21,020","22,280","22,280","28,260",NaN,NaN,NaN,NaN
861920,99,72,Puerto Rico,999300,"Local Government, excluding Schools and Hospit...",4-digit,53-7065,Stockers and Order Fillers,detailed,300,...,13.84,"19,760","20,240","22,270","25,680","28,780",NaN,NaN,NaN,NaN
861921,99,72,Puerto Rico,999300,"Local Government, excluding Schools and Hospit...",4-digit,53-7081,Refuse and Recyclable Material Collectors,detailed,440,...,14.94,"19,760","19,760","19,760","20,130","31,070",NaN,NaN,NaN,NaN

In [4]:
sectors_df.shape

(861922, 29)

In [5]:
sectors_df.columns.tolist()

['naics2',
 'AREA',
 'AREA_TITLE',
 'NAICS',
 'NAICS_TITLE',
 'I_GROUP',
 'OCC_CODE',
 'OCC_TITLE',
 'O_GROUP',
 'TOT_EMP',
 'EMP_PRSE',
 'PCT_TOTAL',
 'H_MEAN',
 'A_MEAN',
 'MEAN_PRSE',
 'H_PCT10',
 'H_PCT25',
 'H_MEDIAN',
 'H_PCT75',
 'H_PCT90',
 'A_PCT10',
 'A_PCT25',
 'A_MEDIAN',
 'A_PCT75',
 'A_PCT90',
 'ANNUAL',
 'HOURLY',
 'Unnamed: 27',
 'release']

In [6]:
df = sectors_df.copy()
# sector_types_df = df.groupby(['I_GROUP']).nunique()
sectors_types_df = df[df['I_GROUP'] == 'sector']
sectors_types_df.head(5)

,naics2,AREA,AREA_TITLE,NAICS,NAICS_TITLE,I_GROUP,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,...,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY,Unnamed: 27,release
0,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,00-0000,All Occupations,total,"5,260",...,35.25,"28,730","36,410","47,560","57,030","73,310",NaN,NaN,NaN,NaN
1,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,11-0000,Management Occupations,major,100,...,68.43,"75,140","85,870","102,590","124,420","142,340",NaN,NaN,NaN,NaN
2,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,11-1021,General and Operations Managers,detailed,70,...,75.46,"73,810","83,810","97,570","130,280","156,960",NaN,NaN,NaN,NaN
3,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,13-0000,Business and Financial Operations Occupations,major,60,...,62.61,"43,180","50,890","72,920","81,470","130,220",NaN,NaN,NaN,NaN
4,11,1,Alabama,11,"Agriculture, Forestry, Fishing and Hunting",sector,19-0000,"Life, Physical, and Social Science Occupations",major,90,...,43.69,"39,970","54,610","57,000","82,080","90,880",NaN,NaN,NaN,NaN

In [7]:
sectors_list_df = sectors_types_df[['NAICS', 'NAICS_TITLE']].drop_duplicates().reset_index(drop=True)
# pd.set_option('display.max_rows', None)
sectors_list_df

    NAICS                                        NAICS_TITLE
0      11         Agriculture, Forestry, Fishing and Hunting
1      21      Mining, Quarrying, and Oil and Gas Extraction
2      22                                          Utilities
3      23                                       Construction
4   31-33                                      Manufacturing
5      42                                    Wholesale Trade
6   44-45                                       Retail Trade
7   48-49                     Transportation and Warehousing
8      51                                        Information
9      52                              Finance and Insurance
10     53                 Real Estate and Rental and Leasing
11     54   Professional, Scientific, and Technical Services
12     55            Management of Companies and Enterprises
13     56  Administrative and Support and Waste Managemen...
14     61                               Educational Services
15     62                  Health Care and Social Assistance
16     71                Arts, Entertainment, and Recreation
17     72                    Accommodation and Food Services
18     81      Other Services (except Public Administration)
19     99  Federal, State, and Local Government, excludin...

In [8]:
## National Employment by Sector 
occur_df = sectors_types_df.copy()
occur_df['TOT_EMP'] = pd.to_numeric(occur_df['TOT_EMP'], errors='coerce')
occur_df = occur_df.groupby('NAICS_TITLE')['TOT_EMP'].sum().reset_index()
occur_df = occur_df.sort_values(by='TOT_EMP', ascending=False)
occur_df

                                          NAICS_TITLE    TOT_EMP
6   Federal, State, and Local Government, excludin...  2731880.0
11                                      Manufacturing  2259750.0
8                   Health Care and Social Assistance  2211940.0
5                                Educational Services  2056600.0
1   Administrative and Support and Waste Managemen...  1706540.0
14   Professional, Scientific, and Technical Services  1670250.0
13      Other Services (except Public Administration)  1516770.0
16                                       Retail Trade  1345440.0
19                                    Wholesale Trade  1301890.0
10            Management of Companies and Enterprises  1208360.0
4                                        Construction  1201630.0
17                     Transportation and Warehousing  1102040.0
3                 Arts, Entertainment, and Recreation  1045850.0
7                               Finance and Insurance   970880.0
9                                         Information   968290.0
0                     Accommodation and Food Services   712640.0
15                 Real Estate and Rental and Leasing   691250.0
18                                          Utilities   502600.0
12      Mining, Quarrying, and Oil and Gas Extraction   360900.0
2          Agriculture, Forestry, Fishing and Hunting   207240.0

In [46]:
## Massachusetts Employment by Sector 
ma_emp_df = sectors_types_df[sectors_types_df['AREA_TITLE'] == 'Massachusetts'].copy()
ma_emp_df['TOT_EMP'] = pd.to_numeric(ma_emp_df['TOT_EMP'], errors='coerce')
ma_emp_df = ma_emp_df.groupby('NAICS_TITLE')['TOT_EMP'].sum().reset_index()
ma_emp_df = ma_emp_df.sort_values(by='TOT_EMP', ascending=False)
ma_emp_df

                                          NAICS_TITLE  TOT_EMP
5                                Educational Services  59150.0
11                                      Manufacturing  54490.0
6   Federal, State, and Local Government, excludin...  49490.0
8                   Health Care and Social Assistance  49470.0
14   Professional, Scientific, and Technical Services  42330.0
10            Management of Companies and Enterprises  36680.0
1   Administrative and Support and Waste Managemen...  33750.0
16                                       Retail Trade  29880.0
13      Other Services (except Public Administration)  29510.0
4                                        Construction  26970.0
19                                    Wholesale Trade  25890.0
9                                         Information  25840.0
3                 Arts, Entertainment, and Recreation  22120.0
17                     Transportation and Warehousing  19890.0
7                               Finance and Insurance  18500.0
15                 Real Estate and Rental and Leasing  16610.0
0                     Accommodation and Food Services  15720.0
18                                          Utilities  11310.0
12      Mining, Quarrying, and Oil and Gas Extraction   2640.0
2          Agriculture, Forestry, Fishing and Hunting   1940.0

In [47]:
## New York Employment by Sector 
ny_emp_df = sectors_types_df[sectors_types_df['AREA_TITLE'] == 'New York'].copy()
ny_emp_df['TOT_EMP'] = pd.to_numeric(ny_emp_df['TOT_EMP'], errors='coerce')
ny_emp_df = ny_emp_df.groupby('NAICS_TITLE')['TOT_EMP'].sum().reset_index()
ny_emp_df = ny_emp_df.sort_values(by='TOT_EMP', ascending=False)
ny_emp_df

                                          NAICS_TITLE  TOT_EMP
6   Federal, State, and Local Government, excludin...  70530.0
11                                      Manufacturing  63680.0
8                   Health Care and Social Assistance  58190.0
5                                Educational Services  57190.0
1   Administrative and Support and Waste Managemen...  56810.0
14   Professional, Scientific, and Technical Services  48730.0
13      Other Services (except Public Administration)  44770.0
16                                       Retail Trade  41370.0
10            Management of Companies and Enterprises  41140.0
19                                    Wholesale Trade  39070.0
3                 Arts, Entertainment, and Recreation  35170.0
17                     Transportation and Warehousing  33790.0
4                                        Construction  32250.0
9                                         Information  28250.0
7                               Finance and Insurance  24130.0
15                 Real Estate and Rental and Leasing  22880.0
0                     Accommodation and Food Services  20680.0
18                                          Utilities  16370.0
12      Mining, Quarrying, and Oil and Gas Extraction   6180.0
2          Agriculture, Forestry, Fishing and Hunting   4720.0

In [11]:
info_df = sectors_df[sectors_df['NAICS_TITLE'] == 'Information']
finance_df = sectors_df[sectors_df['NAICS_TITLE'] == 'Finance and Insurance']
sci_df = sectors_df[sectors_df['NAICS_TITLE'] == 'Professional, Scientific, and Technical Services']
health_df = sectors_df[sectors_df['NAICS_TITLE'] == 'Health Care and Social Assistance']
retail_df = sectors_df[sectors_df['NAICS_TITLE'] == 'Retail Trade']

In [12]:
## Information
ma_info_df = info_df[(info_df['AREA_TITLE'] == 'Massachusetts') & (info_df['NAICS_TITLE'] == 'Information')].copy()
ma_info_df = ma_info_df.sort_values(by='PCT_TOTAL', ascending=False)
ma_info_df_major = ma_info_df[ma_info_df['O_GROUP'] == 'major']
ma_info_df_detailed = ma_info_df[ma_info_df['O_GROUP'] == 'detailed']

In [13]:
## Finance and Insurance
ma_finance_df = finance_df[(finance_df['AREA_TITLE'] == 'Massachusetts') & (finance_df['NAICS_TITLE'] == 'Finance and Insurance')].copy()
ma_finance_df = ma_finance_df.sort_values(by='PCT_TOTAL', ascending=False)
ma_finance_df_major = ma_finance_df[ma_finance_df['O_GROUP'] == 'major']
ma_finance_df_detailed = ma_finance_df[ma_finance_df['O_GROUP'] == 'detailed']

In [14]:
## Professional, Scientific, and Technical Services
ma_sci_df = sci_df[(sci_df['AREA_TITLE'] == 'Massachusetts') & (sci_df['NAICS_TITLE'] == 'Professional, Scientific, and Technical Services')].copy()
ma_sci_df = ma_sci_df.sort_values(by='PCT_TOTAL', ascending=False)
ma_sci_df_major = ma_sci_df[ma_sci_df['O_GROUP'] == 'major']
ma_sci_df_detailed = ma_sci_df[ma_sci_df['O_GROUP'] == 'detailed']

In [15]:
## Health Care and Social Assistance 
ma_health_df = health_df[(health_df['AREA_TITLE'] == 'Massachusetts') & (health_df['NAICS_TITLE'] == 'Health Care and Social Assistance')].copy()
ma_health_df = ma_health_df.sort_values(by='PCT_TOTAL', ascending=False)
ma_health_df_major = ma_health_df[ma_health_df['O_GROUP'] == 'major']
ma_health_df_detailed = ma_health_df[ma_health_df['O_GROUP'] == 'detailed']

In [16]:
## Retail Trade
ma_retail_df = retail_df[(retail_df['AREA_TITLE'] == 'Massachusetts') & (retail_df['NAICS_TITLE'] == 'Retail Trade')].copy()
ma_retail_df = ma_retail_df.sort_values(by='PCT_TOTAL', ascending=False)
ma_retail_df_major = ma_retail_df[ma_retail_df['O_GROUP'] == 'major']
ma_retail_df_detailed = ma_retail_df[ma_retail_df['O_GROUP'] == 'detailed']

In [17]:
ma_info_df_major['PCT_TOTAL'] = pd.to_numeric(ma_info_df_major['PCT_TOTAL'], errors='coerce')
ma_info_df_major = ma_info_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ma_info_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\724303183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_info_df_major['PCT_TOTAL'] = pd.to_numeric(ma_info_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
350063,Massachusetts,51,Information,15-0000,major,Computer and Mathematical Occupations,"26,160",27.75,73.10,"152,050"
350029,Massachusetts,51,Information,11-0000,major,Management Occupations,"16,510",17.51,99.64,"207,250"
350121,Massachusetts,51,Information,41-0000,major,Sales and Related Occupations,"14,410",15.28,45.27,"94,160"
350046,Massachusetts,51,Information,13-0000,major,Business and Financial Operations Occupations,"11,120",11.79,54.81,"114,000"
350095,Massachusetts,51,Information,27-0000,major,"Arts, Design, Entertainment, Sports, and Media...","8,630",9.16,42.46,"88,310"

In [18]:
ma_info_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_info_df_detailed['PCT_TOTAL'], errors='coerce')
ma_info_df_detailed = ma_info_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ma_info_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(8)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\196431507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_info_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_info_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
350074,Massachusetts,51,Information,15-1252,detailed,Software Developers,"14,220",15.09,83.09,"172,840"
350126,Massachusetts,51,Information,41-3091,detailed,"Sales Representatives of Services, Except Adve...","10,620",11.27,45.01,"93,620"
350037,Massachusetts,51,Information,11-3021,detailed,Computer and Information Systems Managers,"4,500",4.78,111.20,"231,300"
350031,Massachusetts,51,Information,11-1021,detailed,General and Operations Managers,"4,200",4.46,89.98,"187,160"
350058,Massachusetts,51,Information,13-1161,detailed,Market Research Analysts and Marketing Special...,"4,170",4.43,51.72,"107,580"
350064,Massachusetts,51,Information,15-1211,detailed,Computer Systems Analysts,"2,620",2.78,62.71,"130,430"
350138,Massachusetts,51,Information,43-4051,detailed,Customer Service Representatives,"2,250",2.39,33.59,"69,860"
350033,Massachusetts,51,Information,11-2022,detailed,Sales Managers,"2,230",2.36,98.21,"204,280"

In [19]:
ma_finance_df_major['PCT_TOTAL'] = pd.to_numeric(ma_finance_df_major['PCT_TOTAL'], errors='coerce')
ma_finance_df_major = ma_finance_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ma_finance_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\278956374.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_finance_df_major['PCT_TOTAL'] = pd.to_numeric(ma_finance_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
380748,Massachusetts,52,Finance and Insurance,13-0000,major,Business and Financial Operations Occupations,"52,650",31.68,57.40,"119,400"
380829,Massachusetts,52,Finance and Insurance,43-0000,major,Office and Administrative Support Occupations,"39,330",23.67,28.93,"60,180"
380730,Massachusetts,52,Finance and Insurance,11-0000,major,Management Occupations,"26,270",15.81,105.44,"219,320"
380821,Massachusetts,52,Finance and Insurance,41-0000,major,Sales and Related Occupations,"24,320",14.63,48.61,"101,100"
380773,Massachusetts,52,Finance and Insurance,15-0000,major,Computer and Mathematical Occupations,"18,180",10.94,63.14,"131,330"

In [20]:
ma_finance_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_finance_df_detailed['PCT_TOTAL'], errors='coerce')
ma_finance_df_detailed = ma_finance_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ma_finance_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(6)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\3625873148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_finance_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_finance_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
380826,Massachusetts,52,Finance and Insurance,41-3031,detailed,"Securities, Commodities, and Financial Service...","12,740",7.67,45.71,"95,070"
380825,Massachusetts,52,Finance and Insurance,41-3021,detailed,Insurance Sales Agents,"9,690",5.83,49.40,"102,750"
380739,Massachusetts,52,Finance and Insurance,11-3031,detailed,Financial Managers,"9,080",5.46,107.69,"223,990"
380765,Massachusetts,52,Finance and Insurance,13-2051,detailed,Financial and Investment Analysts,"8,940",5.38,68.48,"142,430"
380839,Massachusetts,52,Finance and Insurance,43-4051,detailed,Customer Service Representatives,"7,880",4.74,27.42,"57,030"
380766,Massachusetts,52,Finance and Insurance,13-2052,detailed,Personal Financial Advisors,"7,030",4.23,71.66,"149,050"

In [42]:
ma_sci_df_major['PCT_TOTAL'] = pd.to_numeric(ma_sci_df_major['PCT_TOTAL'], errors='coerce')
ma_sci_df_major = ma_sci_df_major.sort_values(by='PCT_TOTAL', ascending=False).drop_duplicates(subset=['OCC_CODE'])
ma_sci_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(10)

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
437893,Massachusetts,54,"Professional, Scientific, and Technical Services",13-0000,major,Business and Financial Operations Occupations,"71,070",19.06,59.47,"123,700"
448145,Massachusetts,541000,"Professional, Scientific, and Technical Services",11-0000,major,Management Occupations,"63,430",17.01,107.19,"222,960"
437918,Massachusetts,54,"Professional, Scientific, and Technical Services",15-0000,major,Computer and Mathematical Occupations,"59,220",15.88,61.44,"127,800"
437970,Massachusetts,54,"Professional, Scientific, and Technical Services",19-0000,major,"Life, Physical, and Social Science Occupations","39,230",10.52,53.64,"111,580"
448215,Massachusetts,541000,"Professional, Scientific, and Technical Services",17-0000,major,Architecture and Engineering Occupations,"36,170",9.70,55.78,"116,020"
448337,Massachusetts,541000,"Professional, Scientific, and Technical Services",43-0000,major,Office and Administrative Support Occupations,"34,850",9.35,31.85,"66,240"
448277,Massachusetts,541000,"Professional, Scientific, and Technical Services",23-0000,major,Legal Occupations,"20,880",5.60,91.65,"190,620"
448326,Massachusetts,541000,"Professional, Scientific, and Technical Services",41-0000,major,Sales and Related Occupations,"14,510",3.89,51.40,"106,910"
448286,Massachusetts,541000,"Professional, Scientific, and Technical Services",27-0000,major,"Arts, Design, Entertainment, Sports, and Media...","9,890",2.65,41.69,"86,720"
448301,Massachusetts,541000,"Professional, Scientific, and Technical Services",29-0000,major,Healthcare Practitioners and Technical Occupat...,"9,510",2.55,47.94,"99,720"

In [43]:
ma_sci_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_sci_df_detailed['PCT_TOTAL'], errors='coerce')
ma_sci_df_detailed = ma_sci_df_detailed.sort_values(by='PCT_TOTAL', ascending=False).drop_duplicates(subset=['OCC_CODE'])
ma_sci_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(20)

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
448206,Massachusetts,541000,"Professional, Scientific, and Technical Services",15-1252,detailed,Software Developers,"20,730",5.56,71.16,"148,020"
437900,Massachusetts,54,"Professional, Scientific, and Technical Services",13-1111,detailed,Management Analysts,"17,690",4.74,78.92,"164,140"
437870,Massachusetts,54,"Professional, Scientific, and Technical Services",11-1021,detailed,General and Operations Managers,"17,530",4.70,105.93,"220,340"
437907,Massachusetts,54,"Professional, Scientific, and Technical Services",13-2011,detailed,Accountants and Auditors,"15,710",4.21,52.21,"108,600"
438001,Massachusetts,54,"Professional, Scientific, and Technical Services",23-1011,detailed,Lawyers,"14,170",3.80,116.61,"242,560"
437972,Massachusetts,54,"Professional, Scientific, and Technical Services",19-1021,detailed,Biochemists and Biophysicists,"12,350",3.31,58.46,"121,590"
437905,Massachusetts,54,"Professional, Scientific, and Technical Services",13-1161,detailed,Market Research Analysts and Marketing Special...,"11,040",2.96,47.75,"99,320"
438055,Massachusetts,54,"Professional, Scientific, and Technical Services",41-3091,detailed,"Sales Representatives of Services, Except Adve...","9,540",2.56,51.81,"107,760"
448155,Massachusetts,541000,"Professional, Scientific, and Technical Services",11-3021,detailed,Computer and Information Systems Managers,"9,180",2.46,102.09,"212,350"
437923,Massachusetts,54,"Professional, Scientific, and Technical Services",15-1232,detailed,Computer User Support Specialists,"8,100",2.17,38.89,"80,890"
448167,Massachusetts,541000,"Professional, Scientific, and Technical Services",11-9121,detailed,Natural Sciences Managers,"7,190",1.93,113.84,"236,790"
448176,Massachusetts,541000,"Professional, Scientific, and Technical Services",13-1082,detailed,Project Management Specialists,"7,060",1.89,61.25,"127,400"
437977,Massachusetts,54,"Professional, Scientific, and Technical Services",19-1042,detailed,"Medical Scientists, Except Epidemiologists","6,240",1.67,69.12,"143,760"
448266,Massachusetts,541000,"Professional, Scientific, and Technical Services",19-4021,detailed,Biological Technicians,"6,140",1.65,34.81,"72,410"
438002,Massachusetts,54,"Professional, Scientific, and Technical Services",23-2011,detailed,Paralegals and Legal Assistants,"6,170",1.65,37.34,"77,660"
437919,Massachusetts,54,"Professional, Scientific, and Technical Services",15-1211,detailed,Computer Systems Analysts,"6,060",1.63,64.53,"134,220"
448223,Massachusetts,541000,"Professional, Scientific, and Technical Services",17-2051,detailed,Civil Engineers,"5,770",1.55,57.71,"120,040"
448156,Massachusetts,541000,"Professional, Scientific, and Technical Services",11-3031,detailed,Financial Managers,"5,460",1.46,110.69,"230,220"
448341,Massachusetts,541000,"Professional, Scientific, and Technical Services",43-3031,detailed,"Bookkeeping, Accounting, and Auditing Clerks","4,800",1.29,28.85,"60,010"
438080,Massachusetts,54,"Professional, Scientific, and Technical Services",43-6014,detailed,"Secretaries and Administrative Assistants, Exc...","4,550",1.22,28.46,"59,190"

In [23]:
ma_health_df_major['PCT_TOTAL'] = pd.to_numeric(ma_health_df_major['PCT_TOTAL'], errors='coerce')
ma_health_df_major = ma_health_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ma_health_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\2633229593.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_health_df_major['PCT_TOTAL'] = pd.to_numeric(ma_health_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
615697,Massachusetts,62,Health Care and Social Assistance,29-0000,major,Healthcare Practitioners and Technical Occupat...,"205,110",31.38,58.83,"122,360"
615762,Massachusetts,62,Health Care and Social Assistance,31-0000,major,Healthcare Support Occupations,"171,610",26.25,21.20,"44,100"
615820,Massachusetts,62,Health Care and Social Assistance,43-0000,major,Office and Administrative Support Occupations,"71,600",10.95,25.65,"53,350"
615654,Massachusetts,62,Health Care and Social Assistance,21-0000,major,Community and Social Service Occupations,"50,310",7.70,29.71,"61,800"
615576,Massachusetts,62,Health Care and Social Assistance,11-0000,major,Management Occupations,"37,390",5.72,61.77,"128,480"

In [24]:
ma_health_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_health_df_detailed['PCT_TOTAL'], errors='coerce')
ma_health_df_detailed = ma_health_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ma_health_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\185437700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_health_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_health_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
615763,Massachusetts,62,Health Care and Social Assistance,31-1120,detailed,Home Health and Personal Care Aides,"99,130",15.16,19.08,"39,680"
615713,Massachusetts,62,Health Care and Social Assistance,29-1141,detailed,Registered Nurses,"77,560",11.86,54.53,"113,420"
615764,Massachusetts,62,Health Care and Social Assistance,31-1131,detailed,Nursing Assistants,"35,270",5.40,21.87,"45,480"
615841,Massachusetts,62,Health Care and Social Assistance,43-6013,detailed,Medical Secretaries and Administrative Assistants,"19,950",3.05,24.75,"51,480"
615658,Massachusetts,62,Health Care and Social Assistance,21-1018,detailed,"Substance Abuse, Behavioral Disorder, and Ment...","16,680",2.55,30.65,"63,750"

In [25]:
ma_retail_df_major['PCT_TOTAL'] = pd.to_numeric(ma_retail_df_major['PCT_TOTAL'], errors='coerce')
ma_retail_df_major = ma_retail_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ma_retail_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\1149666247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_retail_df_major['PCT_TOTAL'] = pd.to_numeric(ma_retail_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
276073,Massachusetts,44-45,Retail Trade,41-0000,major,Sales and Related Occupations,"160,050",48.82,20.03,"41,670"
276141,Massachusetts,44-45,Retail Trade,53-0000,major,Transportation and Material Moving Occupations,"64,230",19.59,19.31,"40,160"
276084,Massachusetts,44-45,Retail Trade,43-0000,major,Office and Administrative Support Occupations,"25,350",7.73,22.60,"47,010"
276000,Massachusetts,44-45,Retail Trade,11-0000,major,Management Occupations,"16,590",5.06,53.93,"112,170"
276107,Massachusetts,44-45,Retail Trade,49-0000,major,"Installation, Maintenance, and Repair Occupations","14,330",4.37,28.95,"60,220"

In [26]:
ma_retail_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_retail_df_detailed['PCT_TOTAL'], errors='coerce')
ma_retail_df_detailed = ma_retail_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ma_retail_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(6)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\3258787460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ma_retail_df_detailed['PCT_TOTAL'] = pd.to_numeric(ma_retail_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
276079,Massachusetts,44-45,Retail Trade,41-2031,detailed,Retail Salespersons,"78,790",24.03,19.47,"40,490"
276076,Massachusetts,44-45,Retail Trade,41-2011,detailed,Cashiers,"54,470",16.62,17.29,"35,950"
276153,Massachusetts,44-45,Retail Trade,53-7065,detailed,Stockers and Order Fillers,"40,450",12.34,19.04,"39,590"
276074,Massachusetts,44-45,Retail Trade,41-1011,detailed,First-Line Supervisors of Retail Sales Workers,"18,990",5.79,28.15,"58,560"
276002,Massachusetts,44-45,Retail Trade,11-1021,detailed,General and Operations Managers,"12,560",3.83,49.53,"103,030"
276089,Massachusetts,44-45,Retail Trade,43-4051,detailed,Customer Service Representatives,"10,610",3.24,20.09,"41,780"

In [27]:
## NYC
ny_info_df = info_df[(info_df['AREA_TITLE'] == 'New York') & (info_df['NAICS_TITLE'] == 'Information')].copy()
ny_info_df = ny_info_df.sort_values(by='PCT_TOTAL', ascending=False)
ny_info_df_major = ny_info_df[ny_info_df['O_GROUP'] == 'major']
ny_info_df_detailed = ny_info_df[ny_info_df['O_GROUP'] == 'detailed']

In [28]:
ny_finance_df = finance_df[(finance_df['AREA_TITLE'] == 'New York') & (finance_df['NAICS_TITLE'] == 'Finance and Insurance')].copy()
ny_finance_df = ny_finance_df.sort_values(by='PCT_TOTAL', ascending=False)
ny_finance_df_major = ny_finance_df[ny_finance_df['O_GROUP'] == 'major']
ny_finance_df_detailed = ny_finance_df[ny_finance_df['O_GROUP'] == 'detailed']

In [29]:
ny_sci_df = sci_df[(sci_df['AREA_TITLE'] == 'New York') & (sci_df['NAICS_TITLE'] == 'Professional, Scientific, and Technical Services')].copy()
ny_sci_df = ny_sci_df.sort_values(by='PCT_TOTAL', ascending=False)
ny_sci_df_major = ny_sci_df[ny_sci_df['O_GROUP'] == 'major']
ny_sci_df_detailed = ny_sci_df[ny_sci_df['O_GROUP'] == 'detailed']

In [30]:
## Health Care and Social Assistance 
ny_health_df = health_df[(health_df['AREA_TITLE'] == 'New York') & (health_df['NAICS_TITLE'] == 'Health Care and Social Assistance')].copy()
ny_health_df = ny_health_df.sort_values(by='PCT_TOTAL', ascending=False)
ny_health_df_major = ny_health_df[ny_health_df['O_GROUP'] == 'major']
ny_health_df_detailed = ny_health_df[ny_health_df['O_GROUP'] == 'detailed']

In [31]:
ny_retail_df = retail_df[(retail_df['AREA_TITLE'] == 'New York') & (retail_df['NAICS_TITLE'] == 'Retail Trade')].copy()
ny_retail_df = ny_retail_df.sort_values(by='PCT_TOTAL', ascending=False)
ny_retail_df_major = ny_retail_df[ny_retail_df['O_GROUP'] == 'major']
ny_retail_df_detailed = ny_retail_df[ny_retail_df['O_GROUP'] == 'detailed']

In [32]:
ny_info_df_major['PCT_TOTAL'] = pd.to_numeric(ny_info_df_major['PCT_TOTAL'], errors='coerce')
ny_info_df_major = ny_info_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ny_info_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(6)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\2451461905.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_info_df_major['PCT_TOTAL'] = pd.to_numeric(ny_info_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
351213,New York,51,Information,27-0000,major,"Arts, Design, Entertainment, Sports, and Media...","63,270",23.36,65.12,"135,440"
351172,New York,51,Information,15-0000,major,Computer and Mathematical Occupations,"51,550",19.03,72.45,"150,690"
351133,New York,51,Information,11-0000,major,Management Occupations,"34,510",12.74,116.12,"241,530"
351153,New York,51,Information,13-0000,major,Business and Financial Operations Occupations,"33,710",12.45,54.56,"113,490"
351262,New York,51,Information,41-0000,major,Sales and Related Occupations,"30,230",11.16,60.83,"126,520"
351276,New York,51,Information,43-0000,major,Office and Administrative Support Occupations,"28,920",10.68,30.47,"63,370"

In [33]:
ny_info_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_info_df_detailed['PCT_TOTAL'], errors='coerce')
ny_info_df_detailed = ny_info_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ny_info_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(7)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\3888682453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_info_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_info_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
351183,New York,51,Information,15-1252,detailed,Software Developers,"27,100",10.01,83.84,"174,380"
351221,New York,51,Information,27-2012,detailed,Producers and Directors,"20,400",7.53,68.24,"141,940"
351269,New York,51,Information,41-3091,detailed,"Sales Representatives of Services, Except Adve...","19,070",7.04,62.54,"130,080"
351226,New York,51,Information,27-3041,detailed,Editors,"12,420",4.59,56.88,"118,310"
351165,New York,51,Information,13-1161,detailed,Market Research Analysts and Marketing Special...,"10,980",4.05,50.23,"104,470"
351283,New York,51,Information,43-4051,detailed,Customer Service Representatives,"9,260",3.42,32.41,"67,420"
351142,New York,51,Information,11-3021,detailed,Computer and Information Systems Managers,"7,640",2.82,120.46,"250,560"

In [34]:
ny_finance_df_major['PCT_TOTAL'] = pd.to_numeric(ny_finance_df_major['PCT_TOTAL'], errors='coerce')
ny_finance_df_major = ny_finance_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ny_finance_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\4163379341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_finance_df_major['PCT_TOTAL'] = pd.to_numeric(ny_finance_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
381880,New York,52,Finance and Insurance,13-0000,major,Business and Financial Operations Occupations,"171,290",32.90,73.14,"152,130"
381979,New York,52,Finance and Insurance,43-0000,major,Office and Administrative Support Occupations,"113,660",21.83,31.80,"66,150"
381862,New York,52,Finance and Insurance,11-0000,major,Management Occupations,"84,500",16.23,127.54,"265,280"
381969,New York,52,Finance and Insurance,41-0000,major,Sales and Related Occupations,"81,160",15.59,82.30,"171,190"
381906,New York,52,Finance and Insurance,15-0000,major,Computer and Mathematical Occupations,"45,210",8.68,75.47,"156,970"

In [35]:
ny_finance_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_finance_df_detailed['PCT_TOTAL'], errors='coerce')
ny_finance_df_detailed = ny_finance_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ny_finance_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\1212518805.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_finance_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_finance_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
381973,New York,52,Finance and Insurance,41-3031,detailed,"Securities, Commodities, and Financial Service...","57,240",10.99,94.51,"196,570"
381871,New York,52,Finance and Insurance,11-3031,detailed,Financial Managers,"31,490",6.05,128.09,"266,430"
381898,New York,52,Finance and Insurance,13-2051,detailed,Financial and Investment Analysts,"31,270",6.00,76.60,"159,320"
381899,New York,52,Finance and Insurance,13-2052,detailed,Personal Financial Advisors,"28,130",5.40,109.67,"228,110"
381990,New York,52,Finance and Insurance,43-4051,detailed,Customer Service Representatives,"28,060",5.39,27.84,"57,900"

In [44]:
ny_sci_df_major['PCT_TOTAL'] = pd.to_numeric(ny_sci_df_major['PCT_TOTAL'], errors='coerce')
ny_sci_df_major = ny_sci_df_major.sort_values(by='PCT_TOTAL', ascending=False).drop_duplicates(subset=['OCC_CODE'])
ny_sci_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']]

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
440035,New York,54,"Professional, Scientific, and Technical Services",13-0000,major,Business and Financial Operations Occupations,"149,840",20.93,54.31,"112,960"
440244,New York,54,"Professional, Scientific, and Technical Services",43-0000,major,Office and Administrative Support Occupations,"106,150",14.83,30.43,"63,300"
440061,New York,54,"Professional, Scientific, and Technical Services",15-0000,major,Computer and Mathematical Occupations,"93,210",13.02,59.91,"124,610"
450431,New York,541000,"Professional, Scientific, and Technical Services",23-0000,major,Legal Occupations,"83,530",11.67,85.10,"177,010"
450287,New York,541000,"Professional, Scientific, and Technical Services",11-0000,major,Management Occupations,"82,120",11.47,104.07,"216,460"
440082,New York,54,"Professional, Scientific, and Technical Services",17-0000,major,Architecture and Engineering Occupations,"48,980",6.84,51.37,"106,850"
450443,New York,541000,"Professional, Scientific, and Technical Services",27-0000,major,"Arts, Design, Entertainment, Sports, and Media...","41,950",5.86,50.66,"105,360"
450508,New York,541000,"Professional, Scientific, and Technical Services",41-0000,major,Sales and Related Occupations,"39,530",5.52,51.00,"106,080"
440113,New York,54,"Professional, Scientific, and Technical Services",19-0000,major,"Life, Physical, and Social Science Occupations","25,360",3.54,41.36,"86,030"
450468,New York,541000,"Professional, Scientific, and Technical Services",29-0000,major,Healthcare Practitioners and Technical Occupat...,"11,130",1.56,49.32,"102,580"
450556,New York,541000,"Professional, Scientific, and Technical Services",47-0000,major,Construction and Extraction Occupations,"5,860",0.82,43.65,"90,780"
450483,New York,541000,"Professional, Scientific, and Technical Services",31-0000,major,Healthcare Support Occupations,"5,840",0.82,21.28,"44,250"
450579,New York,541000,"Professional, Scientific, and Technical Services",51-0000,major,Production Occupations,"4,920",0.69,27.99,"58,210"
450568,New York,541000,"Professional, Scientific, and Technical Services",49-0000,major,"Installation, Maintenance, and Repair Occupations","4,820",0.67,32.24,"67,050"
440319,New York,54,"Professional, Scientific, and Technical Services",53-0000,major,Transportation and Material Moving Occupations,"3,150",0.44,25.72,"53,500"
450437,New York,541000,"Professional, Scientific, and Technical Services",25-0000,major,Educational Instruction and Library Occupations,"2,120",0.30,45.75,"95,150"
450500,New York,541000,"Professional, Scientific, and Technical Services",37-0000,major,Building and Grounds Cleaning and Maintenance ...,"2,090",0.29,23.80,"49,500"
440145,New York,54,"Professional, Scientific, and Technical Services",21-0000,major,Community and Social Service Occupations,"1,630",0.23,37.32,"77,620"
450490,New York,541000,"Professional, Scientific, and Technical Services",33-0000,major,Protective Service Occupations,"1,510",0.21,34.02,"70,760"
440228,New York,54,"Professional, Scientific, and Technical Services",39-0000,major,Personal Care and Service Occupations,"1,340",0.19,19.81,"41,200"
450495,New York,541000,"Professional, Scientific, and Technical Services",35-0000,major,Food Preparation and Serving Related Occupations,680,0.10,19.89,"41,380"
450554,New York,541000,"Professional, Scientific, and Technical Services",45-0000,major,"Farming, Fishing, and Forestry Occupations",80,0.01,25.94,"53,950"

In [45]:
ny_sci_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_sci_df_detailed['PCT_TOTAL'], errors='coerce')
ny_sci_df_detailed = ny_sci_df_detailed.sort_values(by='PCT_TOTAL', ascending=False).drop_duplicates(subset=['OCC_CODE'])
ny_sci_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(12)

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
450432,New York,541000,"Professional, Scientific, and Technical Services",23-1011,detailed,Lawyers,"58,950",8.23,105.88,"220,220"
450328,New York,541000,"Professional, Scientific, and Technical Services",13-2011,detailed,Accountants and Auditors,"39,190",5.48,56.28,"117,050"
450349,New York,541000,"Professional, Scientific, and Technical Services",15-1252,detailed,Software Developers,"35,850",5.01,73.70,"153,300"
440044,New York,54,"Professional, Scientific, and Technical Services",13-1111,detailed,Management Analysts,"30,510",4.26,62.98,"131,000"
450289,New York,541000,"Professional, Scientific, and Technical Services",11-1021,detailed,General and Operations Managers,"23,660",3.31,105.03,"218,460"
450434,New York,541000,"Professional, Scientific, and Technical Services",23-2011,detailed,Paralegals and Legal Assistants,"23,220",3.24,35.15,"73,100"
440238,New York,54,"Professional, Scientific, and Technical Services",41-3091,detailed,"Sales Representatives of Services, Except Adve...","23,060",3.22,51.09,"106,260"
450326,New York,541000,"Professional, Scientific, and Technical Services",13-1161,detailed,Market Research Analysts and Marketing Special...,"22,720",3.17,47.12,"98,010"
450320,New York,541000,"Professional, Scientific, and Technical Services",13-1082,detailed,Project Management Specialists,"17,820",2.49,57.61,"119,820"
450291,New York,541000,"Professional, Scientific, and Technical Services",11-2021,detailed,Marketing Managers,"15,600",2.18,90.27,"187,760"
440265,New York,54,"Professional, Scientific, and Technical Services",43-6012,detailed,Legal Secretaries and Administrative Assistants,"13,370",1.87,34.57,"71,910"
450343,New York,541000,"Professional, Scientific, and Technical Services",15-1232,detailed,Computer User Support Specialists,"13,250",1.85,32.94,"68,520"

In [38]:
ny_health_df_major['PCT_TOTAL'] = pd.to_numeric(ny_health_df_major['PCT_TOTAL'], errors='coerce')
ny_health_df_major = ny_health_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ny_health_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\1083942687.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_health_df_major['PCT_TOTAL'] = pd.to_numeric(ny_health_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
618415,New York,62,Health Care and Social Assistance,31-0000,major,Healthcare Support Occupations,"762,230",40.90,19.94,"41,470"
618346,New York,62,Health Care and Social Assistance,29-0000,major,Healthcare Practitioners and Technical Occupat...,"449,830",24.14,58.69,"122,070"
618476,New York,62,Health Care and Social Assistance,43-0000,major,Office and Administrative Support Occupations,"210,940",11.32,25.81,"53,690"
618304,New York,62,Health Care and Social Assistance,21-0000,major,Community and Social Service Occupations,"110,030",5.90,31.54,"65,600"
618323,New York,62,Health Care and Social Assistance,25-0000,major,Educational Instruction and Library Occupations,"66,200",3.55,25.60,"53,240"

In [39]:
ny_health_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_health_df_detailed['PCT_TOTAL'], errors='coerce')
ny_health_df_detailed = ny_health_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ny_health_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\2732131877.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_health_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_health_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
618416,New York,62,Health Care and Social Assistance,31-1120,detailed,Home Health and Personal Care Aides,"599,950",32.20,18.99,"39,510"
618365,New York,62,Health Care and Social Assistance,29-1141,detailed,Registered Nurses,"157,410",8.45,53.35,"110,960"
618417,New York,62,Health Care and Social Assistance,31-1131,detailed,Nursing Assistants,"73,000",3.92,22.76,"47,340"
618493,New York,62,Health Care and Social Assistance,43-4171,detailed,Receptionists and Information Clerks,"40,850",2.19,21.22,"44,130"
618426,New York,62,Health Care and Social Assistance,31-9092,detailed,Medical Assistants,"34,700",1.86,22.81,"47,430"

In [40]:
ny_retail_df_major['PCT_TOTAL'] = pd.to_numeric(ny_retail_df_major['PCT_TOTAL'], errors='coerce')
ny_retail_df_major = ny_retail_df_major.sort_values(by='PCT_TOTAL', ascending=False)
ny_retail_df_major[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\4085361454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_retail_df_major['PCT_TOTAL'] = pd.to_numeric(ny_retail_df_major['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
277831,New York,44-45,Retail Trade,41-0000,major,Sales and Related Occupations,"413,620",49.10,20.94,"43,560"
277937,New York,44-45,Retail Trade,53-0000,major,Transportation and Material Moving Occupations,"138,490",16.44,19.52,"40,610"
277843,New York,44-45,Retail Trade,43-0000,major,Office and Administrative Support Occupations,"70,010",8.31,23.39,"48,640"
277710,New York,44-45,Retail Trade,11-0000,major,Management Occupations,"41,030",4.87,57.09,"118,750"
277790,New York,44-45,Retail Trade,29-0000,major,Healthcare Practitioners and Technical Occupat...,"37,400",4.44,36.61,"76,140"

In [41]:
ny_retail_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_retail_df_detailed['PCT_TOTAL'], errors='coerce')
ny_retail_df_detailed = ny_retail_df_detailed.sort_values(by='PCT_TOTAL', ascending=False)
ny_retail_df_detailed[['AREA_TITLE', 'NAICS', 'NAICS_TITLE', 'OCC_CODE', 'O_GROUP', 'OCC_TITLE', 'TOT_EMP', 'PCT_TOTAL', 'H_MEAN', 'A_MEAN']].head(5)

C:\Users\maggi\AppData\Local\Temp\ipykernel_21928\1048979733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ny_retail_df_detailed['PCT_TOTAL'] = pd.to_numeric(ny_retail_df_detailed['PCT_TOTAL'], errors='coerce')

,AREA_TITLE,NAICS,NAICS_TITLE,OCC_CODE,O_GROUP,OCC_TITLE,TOT_EMP,PCT_TOTAL,H_MEAN,A_MEAN
277837,New York,44-45,Retail Trade,41-2031,detailed,Retail Salespersons,"213,040",25.29,20.52,"42,690"
277834,New York,44-45,Retail Trade,41-2011,detailed,Cashiers,"132,170",15.69,17.15,"35,670"
277950,New York,44-45,Retail Trade,53-7065,detailed,Stockers and Order Fillers,"92,620",11.00,18.73,"38,960"
277832,New York,44-45,Retail Trade,41-1011,detailed,First-Line Supervisors of Retail Sales Workers,"45,960",5.46,29.59,"61,540"
277712,New York,44-45,Retail Trade,11-1021,detailed,General and Operations Managers,"30,960",3.67,48.37,"100,620"

In [61]:
# merge employment data for finance sectors
fi_emp = pd.merge(ny_finance_df_detailed, ma_finance_df_detailed, on='OCC_CODE', suffixes=('_NY', '_MA')).assign(MEAN_PCT_TOTAL=lambda x: (x['PCT_TOTAL_NY'] + x['PCT_TOTAL_MA']) / 2).sort_values(by='MEAN_PCT_TOTAL', ascending=False)
fi_emp[['OCC_CODE', 'OCC_TITLE_NY', 'MEAN_PCT_TOTAL', 'TOT_EMP_NY', 'PCT_TOTAL_NY', 'H_MEAN_NY', 'A_MEAN_NY', 'OCC_TITLE_MA', 'TOT_EMP_MA', 'PCT_TOTAL_MA', 'H_MEAN_MA', 'A_MEAN_MA']].head(10)

,OCC_CODE,OCC_TITLE_NY,MEAN_PCT_TOTAL,TOT_EMP_NY,PCT_TOTAL_NY,H_MEAN_NY,A_MEAN_NY,OCC_TITLE_MA,TOT_EMP_MA,PCT_TOTAL_MA,H_MEAN_MA,A_MEAN_MA
0,41-3031,"Securities, Commodities, and Financial Service...",9.330,"57,240",10.99,94.51,"196,570","Securities, Commodities, and Financial Service...","12,740",7.67,45.71,"95,070"
1,11-3031,Financial Managers,5.755,"31,490",6.05,128.09,"266,430",Financial Managers,"9,080",5.46,107.69,"223,990"
2,13-2051,Financial and Investment Analysts,5.690,"31,270",6.00,76.60,"159,320",Financial and Investment Analysts,"8,940",5.38,68.48,"142,430"
4,43-4051,Customer Service Representatives,5.065,"28,060",5.39,27.84,"57,900",Customer Service Representatives,"7,880",4.74,27.42,"57,030"
5,41-3021,Insurance Sales Agents,4.885,"20,490",3.94,51.26,"106,620",Insurance Sales Agents,"9,690",5.83,49.40,"102,750"
3,13-2052,Personal Financial Advisors,4.815,"28,130",5.40,109.67,"228,110",Personal Financial Advisors,"7,030",4.23,71.66,"149,050"
8,43-3071,Tellers,3.655,"17,120",3.29,21.06,"43,800",Tellers,"6,670",4.02,21.49,"44,710"
6,11-1021,General and Operations Managers,3.290,"19,770",3.80,121.03,"251,750",General and Operations Managers,"4,630",2.78,109.46,"227,670"
9,13-2011,Accountants and Auditors,3.260,"16,670",3.20,70.54,"146,730",Accountants and Auditors,"5,520",3.32,47.29,"98,360"
7,15-1252,Software Developers,3.205,"18,620",3.58,85.95,"178,770",Software Developers,"4,700",2.83,69.50,"144,570"

In [62]:
# merge employment data for pst sector
pst_emp = pd.merge(ny_sci_df_detailed, ma_sci_df_detailed, on='OCC_CODE', suffixes=('_NY', '_MA')).assign(MEAN_PCT_TOTAL=lambda x: (x['PCT_TOTAL_NY'] + x['PCT_TOTAL_MA']) / 2).sort_values(by='MEAN_PCT_TOTAL', ascending=False)
pst_emp[['OCC_CODE', 'OCC_TITLE_NY', 'MEAN_PCT_TOTAL', 'TOT_EMP_NY', 'PCT_TOTAL_NY', 'H_MEAN_NY', 'A_MEAN_NY', 'OCC_TITLE_MA', 'TOT_EMP_MA', 'PCT_TOTAL_MA', 'H_MEAN_MA', 'A_MEAN_MA']].head(10)

,OCC_CODE,OCC_TITLE_NY,MEAN_PCT_TOTAL,TOT_EMP_NY,PCT_TOTAL_NY,H_MEAN_NY,A_MEAN_NY,OCC_TITLE_MA,TOT_EMP_MA,PCT_TOTAL_MA,H_MEAN_MA,A_MEAN_MA
0,23-1011,Lawyers,6.015,"58,950",8.23,105.88,"220,220",Lawyers,"14,170",3.80,116.61,"242,560"
2,15-1252,Software Developers,5.285,"35,850",5.01,73.70,"153,300",Software Developers,"20,730",5.56,71.16,"148,020"
1,13-2011,Accountants and Auditors,4.845,"39,190",5.48,56.28,"117,050",Accountants and Auditors,"15,710",4.21,52.21,"108,600"
3,13-1111,Management Analysts,4.500,"30,510",4.26,62.98,"131,000",Management Analysts,"17,690",4.74,78.92,"164,140"
4,11-1021,General and Operations Managers,4.005,"23,660",3.31,105.03,"218,460",General and Operations Managers,"17,530",4.70,105.93,"220,340"
7,13-1161,Market Research Analysts and Marketing Special...,3.065,"22,720",3.17,47.12,"98,010",Market Research Analysts and Marketing Special...,"11,040",2.96,47.75,"99,320"
6,41-3091,"Sales Representatives of Services, Except Adve...",2.890,"23,060",3.22,51.09,"106,260","Sales Representatives of Services, Except Adve...","9,540",2.56,51.81,"107,760"
5,23-2011,Paralegals and Legal Assistants,2.445,"23,220",3.24,35.15,"73,100",Paralegals and Legal Assistants,"6,170",1.65,37.34,"77,660"
8,13-1082,Project Management Specialists,2.190,"17,820",2.49,57.61,"119,820",Project Management Specialists,"7,060",1.89,61.25,"127,400"
11,15-1232,Computer User Support Specialists,2.010,"13,250",1.85,32.94,"68,520",Computer User Support Specialists,"8,100",2.17,38.89,"80,890"

In [64]:
# merge employment data for retail sector
rt_emp = pd.merge(ny_retail_df_detailed, ma_retail_df_detailed, on='OCC_CODE', suffixes=('_NY', '_MA')).assign(MEAN_PCT_TOTAL=lambda x: (x['PCT_TOTAL_NY'] + x['PCT_TOTAL_MA']) / 2).sort_values(by='MEAN_PCT_TOTAL', ascending=False)
rt_emp[['OCC_CODE', 'OCC_TITLE_NY', 'MEAN_PCT_TOTAL', 'TOT_EMP_NY', 'PCT_TOTAL_NY', 'H_MEAN_NY', 'A_MEAN_NY', 'OCC_TITLE_MA', 'TOT_EMP_MA', 'PCT_TOTAL_MA', 'H_MEAN_MA', 'A_MEAN_MA']].head(10)

,OCC_CODE,OCC_TITLE_NY,MEAN_PCT_TOTAL,TOT_EMP_NY,PCT_TOTAL_NY,H_MEAN_NY,A_MEAN_NY,OCC_TITLE_MA,TOT_EMP_MA,PCT_TOTAL_MA,H_MEAN_MA,A_MEAN_MA
0,41-2031,Retail Salespersons,24.660,"213,040",25.29,20.52,"42,690",Retail Salespersons,"78,790",24.03,19.47,"40,490"
1,41-2011,Cashiers,16.155,"132,170",15.69,17.15,"35,670",Cashiers,"54,470",16.62,17.29,"35,950"
2,53-7065,Stockers and Order Fillers,11.670,"92,620",11.00,18.73,"38,960",Stockers and Order Fillers,"40,450",12.34,19.04,"39,590"
3,41-1011,First-Line Supervisors of Retail Sales Workers,5.625,"45,960",5.46,29.59,"61,540",First-Line Supervisors of Retail Sales Workers,"18,990",5.79,28.15,"58,560"
4,11-1021,General and Operations Managers,3.750,"30,960",3.67,48.37,"100,620",General and Operations Managers,"12,560",3.83,49.53,"103,030"
5,43-4051,Customer Service Representatives,2.860,"20,900",2.48,20.77,"43,190",Customer Service Representatives,"10,610",3.24,20.09,"41,780"
6,29-2052,Pharmacy Technicians,2.465,"20,470",2.43,20.17,"41,960",Pharmacy Technicians,"8,190",2.50,20.23,"42,070"
8,49-3023,Automotive Service Technicians and Mechanics,1.845,"13,730",1.63,28.28,"58,820",Automotive Service Technicians and Mechanics,"6,740",2.06,28.61,"59,520"
7,35-3023,Fast Food and Counter Workers,1.750,"18,520",2.20,18.12,"37,690",Fast Food and Counter Workers,"4,250",1.30,17.81,"37,040"
22,53-7064,"Packers and Packagers, Hand",1.395,"4,850",0.58,19.45,"40,460","Packers and Packagers, Hand","7,260",2.21,16.60,"34,540"

In [65]:
# merge employment data for healthcare sector
hsa_emp = pd.merge(ny_health_df_detailed, ma_health_df_detailed, on='OCC_CODE', suffixes=('_NY', '_MA')).assign(MEAN_PCT_TOTAL=lambda x: (x['PCT_TOTAL_NY'] + x['PCT_TOTAL_MA']) / 2).sort_values(by='MEAN_PCT_TOTAL', ascending=False)
hsa_emp[['OCC_CODE', 'OCC_TITLE_NY', 'MEAN_PCT_TOTAL', 'TOT_EMP_NY', 'PCT_TOTAL_NY', 'H_MEAN_NY', 'A_MEAN_NY', 'OCC_TITLE_MA', 'TOT_EMP_MA', 'PCT_TOTAL_MA', 'H_MEAN_MA', 'A_MEAN_MA']].head(10)

,OCC_CODE,OCC_TITLE_NY,MEAN_PCT_TOTAL,TOT_EMP_NY,PCT_TOTAL_NY,H_MEAN_NY,A_MEAN_NY,OCC_TITLE_MA,TOT_EMP_MA,PCT_TOTAL_MA,H_MEAN_MA,A_MEAN_MA
0,31-1120,Home Health and Personal Care Aides,23.680,"599,950",32.20,18.99,"39,510",Home Health and Personal Care Aides,"99,130",15.16,19.08,"39,680"
1,29-1141,Registered Nurses,10.155,"157,410",8.45,53.35,"110,960",Registered Nurses,"77,560",11.86,54.53,"113,420"
2,31-1131,Nursing Assistants,4.660,"73,000",3.92,22.76,"47,340",Nursing Assistants,"35,270",5.40,21.87,"45,480"
7,43-6013,Medical Secretaries and Administrative Assistants,2.310,"29,230",1.57,23.58,"49,050",Medical Secretaries and Administrative Assistants,"19,950",3.05,24.75,"51,480"
4,31-9092,Medical Assistants,2.100,"34,700",1.86,22.81,"47,430",Medical Assistants,"15,270",2.34,24.02,"49,960"
3,43-4171,Receptionists and Information Clerks,1.875,"40,850",2.19,21.22,"44,130",Receptionists and Information Clerks,"10,230",1.56,21.38,"44,480"
5,29-2061,Licensed Practical and Licensed Vocational Nurses,1.855,"31,340",1.68,31.13,"64,740",Licensed Practical and Licensed Vocational Nurses,"13,260",2.03,36.20,"75,290"
13,21-1018,"Substance Abuse, Behavioral Disorder, and Ment...",1.805,"19,710",1.06,33.31,"69,280","Substance Abuse, Behavioral Disorder, and Ment...","16,680",2.55,30.65,"63,750"
10,11-9111,Medical and Health Services Managers,1.710,"23,300",1.25,87.45,"181,890",Medical and Health Services Managers,"14,210",2.17,69.22,"143,980"
18,25-2011,"Preschool Teachers, Except Special Education",1.420,"17,150",0.92,22.14,"46,040","Preschool Teachers, Except Special Education","12,530",1.92,21.86,"45,460"

In [66]:
# merge employment data for information sector
in_emp = pd.merge(ny_info_df_detailed, ma_info_df_detailed, on='OCC_CODE', suffixes=('_NY', '_MA')).assign(MEAN_PCT_TOTAL=lambda x: (x['PCT_TOTAL_NY'] + x['PCT_TOTAL_MA']) / 2).sort_values(by='MEAN_PCT_TOTAL', ascending=False)
in_emp[['OCC_CODE', 'OCC_TITLE_NY', 'MEAN_PCT_TOTAL', 'TOT_EMP_NY', 'PCT_TOTAL_NY', 'H_MEAN_NY', 'A_MEAN_NY', 'OCC_TITLE_MA', 'TOT_EMP_MA', 'PCT_TOTAL_MA', 'H_MEAN_MA', 'A_MEAN_MA']].head(10)

,OCC_CODE,OCC_TITLE_NY,MEAN_PCT_TOTAL,TOT_EMP_NY,PCT_TOTAL_NY,H_MEAN_NY,A_MEAN_NY,OCC_TITLE_MA,TOT_EMP_MA,PCT_TOTAL_MA,H_MEAN_MA,A_MEAN_MA
0,15-1252,Software Developers,12.550,"27,100",10.01,83.84,"174,380",Software Developers,"14,220",15.09,83.09,"172,840"
2,41-3091,"Sales Representatives of Services, Except Adve...",9.155,"19,070",7.04,62.54,"130,080","Sales Representatives of Services, Except Adve...","10,620",11.27,45.01,"93,620"
1,27-2012,Producers and Directors,4.800,"20,400",7.53,68.24,"141,940",Producers and Directors,"1,950",2.07,47.72,"99,260"
4,13-1161,Market Research Analysts and Marketing Special...,4.240,"10,980",4.05,50.23,"104,470",Market Research Analysts and Marketing Special...,"4,170",4.43,51.72,"107,580"
6,11-3021,Computer and Information Systems Managers,3.800,"7,640",2.82,120.46,"250,560",Computer and Information Systems Managers,"4,500",4.78,111.20,"231,300"
7,11-1021,General and Operations Managers,3.595,"7,390",2.73,116.80,"242,940",General and Operations Managers,"4,200",4.46,89.98,"187,160"
3,27-3041,Editors,3.230,"12,420",4.59,56.88,"118,310",Editors,"1,760",1.87,38.72,"80,530"
5,43-4051,Customer Service Representatives,2.905,"9,260",3.42,32.41,"67,420",Customer Service Representatives,"2,250",2.39,33.59,"69,860"
8,11-2021,Marketing Managers,2.290,"7,060",2.61,103.95,"216,220",Marketing Managers,"1,860",1.97,96.70,"201,130"
9,49-9052,Telecommunications Line Installers and Repairers,2.290,"6,650",2.45,49.46,"102,870",Telecommunications Line Installers and Repairers,"2,010",2.13,49.23,"102,400"